### GET TODOS
GET http://localhost:3000/api/todos/
Authorization: Bearer {{$processEnv BEARER_TOKEN}}

### GET ONE TODO
GET http://localhost:3000/api/todos/2

### POST TODO
POST http://localhost:3000/api/todos/
Content-Type: application/json
Authorization: Bearer {{$processEnv BEARER_TOKEN}}

{
  "title": "tes pake authh 2",
  "description": "mantapp"
}

### UPDATE TODO
PUT http://localhost:3000/api/todos/1
Content-Type: application/json
Authorization: Bearer {{$processEnv BEARER_TOKEN}}

{
  "title": "Update judul lagiii",
  "description": "Update deskripsi"
}

### DELETE TODO
DELETE  http://localhost:3000/api/todos/10
Authorization: Bearer {{$processEnv BEARER_TOKEN}}

